name: ion CI

on:
  pull_request:
    paths:
      - "ion/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/crate-ci.yml"
      - ".github/workflows/ion.yml"
  push:
    branches:
      - dev
      - master
    paths:
      - "ion/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/crate-ci.yml"
      - ".github/workflows/ion.yml"
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/crate-ci.yml
    with:
      package: ion
